### ISSUE TITLE
Windows 10/11: Code crashes when using thumb_side and moving hand up and down

### ISSUE THREAD

**Issue by KingDuken** [jorisparet/hamoco#1]
Code crashes when you utilize the thumb_side gesture and then move your hand up or down. 
Utilizing Python 3.8.10 (but also tested on Python 3.10.4)
Running the code as: `hamoco-run -S 0.1 --min_cutoff_filter 0.5 --minimum_prediction_confidence 0.9 --beta_filter 15 --show`
Warnings upon starting the code:
```
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
ZZZ: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
ZZZ: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
ZZZ: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
ZZZ: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

Traceback after making the code crash:
```
Traceback (most recent call last):
  File "C:/Users/zzz/AppData/Local/Programs/Python/Python38/Scripts/hamoco-run", line 123, in <module>
    hand_controller.operate_mouse(hand,
  File "C:\Users\zzz\AppData\Local\Programs\Python\Python38\lib\site-packages\hamoco\controller.py", line 162, in operate_mouse
    pyautogui.scroll(numpy.sign(diff_to_origin_y), _pause=False)
  File "C:\Users\zzz\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 598, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "C:\Users\zzz\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 1196, in scroll
    platformModule._scroll(clicks, x, y)
  File "C:\Users\zzz\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\_pyautogui_win.py", line 534, in _scroll
    _sendMouseEvent(MOUSEEVENTF_WHEEL, x, y, dwData=clicks)
  File "C:\Users\zzz\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\_pyautogui_win.py", line 495, in _sendMouseEvent
    ctypes.windll.user32.mouse_event(ev, ctypes.c_long(convertedX), ctypes.c_long(convertedY), dwData, 0)
ctypes.ArgumentError: argument 4: <class 'TypeError'>: Don't know how to convert parameter 4
[ WARN:0@45.598] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

```

**Comment by jorisparet** [comment]
Hi @KingDuken and thank you for rising the issue!

The code is still in its very early stages (version 0.0.1) and not "officially" released yet, so I was not expecting that someone would give it a try so soon! But this is useful feedback, so thank you. :smile:

First of all, it appears you are using the code with Windows, which was not tested at all at this point since I'm developing with Linux. So, quick question: **are the other gestures working as expected (moving the mouse, left click, right click, drag&drop)?** The error traces back to the PyAutoGUI external library. If the rest is working and only the scrolling is to blame, it may come from PyAutoGUI directly, which is a bit more complicated for me to solve. But I will look into it.

About the warnings upon starting, it has to do with the way TensorFlow is installed. From my understanding, it's perfectly normal that it behaves this way with a *standard* installation, because the library is optimized for GPU. So it simply tells you that it won't be used at the top of its abilities because it will have to rely on the less adapted CPU computing instead, so nothing to worry about. You can rebuild TensorFlow so it uses the GPU instead (see [here](https://www.tensorflow.org/install/gpu)), but this is not critical.

**Comment by jorisparet** [comment]
I gave it a go on Windows 10 and was able to trace the problem back to an implicit float-to-int conversion that was done on Linux but not on Windows. 

After that, it seems that everything works as expected, with a **small difference** : I introduced a new `scrolling_speed` option in the CLI. The speed was hardcoded to 1 because it's the minimum value accepted on Linux but it strangely corresponds to a pretty large scrolling speed already... Things are scaled quite differently on Windows, where a value of 1 actually represents a *very slow* scrolling speed. So you can now tune this value to something more adapted to your needs (for my test `--scrolling_speed 20` felt like a pretty comfortable value).

Let me know if this fixed the issue on your side as well, or if you have any other issue. :)

All the best.

**Comment by jorisparet** [comment]
Hi @KingDuken! Thanks a lot for your feedback, I'm really glad you like it. 😃 

After dealing with a few more critical aspects of the code, I will try to add guidelines for a proper Windows install.

All the best.
